2021-12-10 12:53:40 Closing network session.
2021-12-10 12:53:40 Network session closed.
2021-12-10 14:41:58 can only concatenate str (not "_Printer") to str
Traceback (most recent call last):
  File "/Users/kimbach/Documents/wikilabskultur/batchupload/smkbatch.py", line 652, in TestSMKAPI
    wikitext = artwork.wikitext + '\n' + license + '\n' + str(smk_categories)
TypeError: can only concatenate str (not "_Printer") to str
2021-12-10 14:41:58 can only concatenate str (not "_Printer") to str
Traceback (most recent call last):
  File "/Users/kimbach/Documents/wikilabskultur/batchupload/smkbatch.py", line 652, in TestSMKAPI
    wikitext = artwork.wikitext + '\n' + license + '\n' + str(smk_categories)
TypeError: can only concatenate str (not "_Printer") to str
2021-12-10 14:41:59 can only concatenate str (not "_Printer") to str
Traceback (most recent call last):
  File "/Users/kimbach/Documents/wikilabskultur/batchupload/smkbatch.py", line 652, in TestSMKAPI
    wikitext = artwork.wikitext + '\n' + license + '\n' + str(smk_categories)
TypeError: can only concatenate str (not "_Printer") to str
2021-12-10 14:41:59 can only concatenate str (not "_Printer") to str
Traceback (most recent call last):
  File "/Users/kimbach/Documents/wikilabskultur/batchupload/smkbatch.py", line 652, in TestSMKAPI
    wikitext = artwork.wikitext + '\n' + license + '\n' + str(smk_categories)
TypeError: can only concatenate str (not "_Printer") to str
2021-12-10 14:41:59 can only concatenate str (not "_Printer") to str
Traceback (most recent call last):
  File "/Users/kimbach/Documents/wikilabskultur/batchupload/smkbatch.py", line 652, in TestSMKAPI
    wikitext = artwork.wikitext + '\n' + license + '\n' + str(smk_categories)
TypeError: can only concatenate str (not "_Printer") to str
2021-12-10 14:42:00 can only concatenate str (not "_Printer") to str
Traceback (most recent call last):
  File "/Users/kimbach/Documents/wikilabskultur/batchupload/smkbatch.py", line 652, in TestSMKAPI
    wikitext = artwork.wikitext + '\n' + license + '\n' + str(smk_categories)
TypeError: can only concatenate str (not "_Printer") to str
2021-12-10 14:42:00 can only concatenate str (not "_Printer") to str
Traceback (most recent call last):
  File "/Users/kimbach/Documents/wikilabskultur/batchupload/smkbatch.py", line 652, in TestSMKAPI
    wikitext = artwork.wikitext + '\n' + license + '\n' + str(smk_categories)
TypeError: can only concatenate str (not "_Printer") to str
2021-12-10 14:42:01 can only concatenate str (not "_Printer") to str
Traceback (most recent call last):
  File "/Users/kimbach/Documents/wikilabskultur/batchupload/smkbatch.py", line 652, in TestSMKAPI
    wikitext = artwork.wikitext + '\n' + license + '\n' + str(smk_categories)
TypeError: can only concatenate str (not "_Printer") to str
2021-12-10 14:42:01 can only concatenate str (not "_Printer") to str
Traceback (most recent call last):
  File "/Users/kimbach/Documents/wikilabskultur/batchupload/smkbatch.py", line 652, in TestSMKAPI
    wikitext = artwork.wikitext + '\n' + license + '\n' + str(smk_categories)
TypeError: can only concatenate str (not "_Printer") to str
2021-12-10 14:42:01 can only concatenate str (not "_Printer") to str
Traceback (most recent call last):
  File "/Users/kimbach/Documents/wikilabskultur/batchupload/smkbatch.py", line 652, in TestSMKAPI
    wikitext = artwork.wikitext + '\n' + license + '\n' + str(smk_categories)
TypeError: can only concatenate str (not "_Printer") to str
2021-12-10 14:42:02 Closing network session.
2021-12-10 14:42:02 Network session closed.
2021-12-10 16:12:55 Closing network session.
2021-12-10 16:12:55 Network session closed.
2021-12-10 17:33:02 Closing network session.
2021-12-10 17:33:02 Network session closed.
2021-12-10 17:34:52 Closing network session.
2021-12-10 17:34:52 Network session closed.
2021-12-10 17:44:39 Closing network session.
2021-12-10 17:44:39 Network session closed.
2021-12-10 18:22:20 HTTPSConnectionPool(host='api.smk.dk', port=443): Read timed out. (read timeout=None)
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/urllib3/connectionpool.py", line 384, in _make_request
    six.raise_from(e, None)
  File "<string>", line 2, in raise_from
  File "/usr/local/lib/python3.7/site-packages/urllib3/connectionpool.py", line 380, in _make_request
    httplib_response = conn.getresponse()
  File "/usr/local/Cellar/python/3.7.2_1/Frameworks/Python.framework/Versions/3.7/lib/python3.7/http/client.py", line 1321, in getresponse
    response.begin()
  File "/usr/local/Cellar/python/3.7.2_1/Frameworks/Python.framework/Versions/3.7/lib/python3.7/http/client.py", line 296, in begin
    version, status, reason = self._read_status()
  File "/usr/local/Cellar/python/3.7.2_1/Frameworks/Python.framework/Versions/3.7/lib/python3.7/http/client.py", line 257, in _read_status
    line = str(self.fp.readline(_MAXLINE + 1), "iso-8859-1")
  File "/usr/local/Cellar/python/3.7.2_1/Frameworks/Python.framework/Versions/3.7/lib/python3.7/socket.py", line 589, in readinto
    return self._sock.recv_into(b)
  File "/usr/local/Cellar/python/3.7.2_1/Frameworks/Python.framework/Versions/3.7/lib/python3.7/ssl.py", line 1052, in recv_into
    return self.read(nbytes, buffer)
  File "/usr/local/Cellar/python/3.7.2_1/Frameworks/Python.framework/Versions/3.7/lib/python3.7/ssl.py", line 911, in read
    return self._sslobj.read(len, buffer)
TimeoutError: [Errno 60] Operation timed out

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/requests/adapters.py", line 449, in send
    timeout=timeout
  File "/usr/local/lib/python3.7/site-packages/urllib3/connectionpool.py", line 638, in urlopen
    _stacktrace=sys.exc_info()[2])
  File "/usr/local/lib/python3.7/site-packages/urllib3/util/retry.py", line 367, in increment
    raise six.reraise(type(error), error, _stacktrace)
  File "/usr/local/lib/python3.7/site-packages/urllib3/packages/six.py", line 686, in reraise
    raise value
  File "/usr/local/lib/python3.7/site-packages/urllib3/connectionpool.py", line 600, in urlopen
    chunked=chunked)
  File "/usr/local/lib/python3.7/site-packages/urllib3/connectionpool.py", line 386, in _make_request
    self._raise_timeout(err=e, url=url, timeout_value=read_timeout)
  File "/usr/local/lib/python3.7/site-packages/urllib3/connectionpool.py", line 317, in _raise_timeout
    raise ReadTimeoutError(self, url, "Read timed out. (read timeout=%s)" % timeout_value)
urllib3.exceptions.ReadTimeoutError: HTTPSConnectionPool(host='api.smk.dk', port=443): Read timed out. (read timeout=None)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/kimbach/Documents/wikilabskultur/batchupload/smkbatch.py", line 207, in TestSMKAPI
    smk_objects=smkapi.get_smk_objects(smk_filter,offset, rows)
  File "/Users/kimbach/Documents/wikilabskultur/batchupload/smkapi.py", line 94, in get_smk_objects
    data=json.loads(requests.get(url).text)
  File "/usr/local/lib/python3.7/site-packages/requests/api.py", line 75, in get
    return request('get', url, params=params, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/requests/api.py", line 60, in request
    return session.request(method=method, url=url, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/requests/sessions.py", line 533, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/local/lib/python3.7/site-packages/requests/sessions.py", line 646, in send
    r = adapter.send(request, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/requests/adapters.py", line 529, in send
    raise ReadTimeout(e, request=request)
requests.exceptions.ReadTimeout: HTTPSConnectionPool(host='api.smk.dk', port=443): Read timed out. (read timeout=None)
2021-12-10 18:40:27 ('Connection aborted.', TimeoutError(60, 'Operation timed out'))
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/urllib3/connectionpool.py", line 600, in urlopen
    chunked=chunked)
  File "/usr/local/lib/python3.7/site-packages/urllib3/connectionpool.py", line 343, in _make_request
    self._validate_conn(conn)
  File "/usr/local/lib/python3.7/site-packages/urllib3/connectionpool.py", line 839, in _validate_conn
    conn.connect()
  File "/usr/local/lib/python3.7/site-packages/urllib3/connection.py", line 344, in connect
    ssl_context=context)
  File "/usr/local/lib/python3.7/site-packages/urllib3/util/ssl_.py", line 344, in ssl_wrap_socket
    return context.wrap_socket(sock, server_hostname=server_hostname)
  File "/usr/local/Cellar/python/3.7.2_1/Frameworks/Python.framework/Versions/3.7/lib/python3.7/ssl.py", line 412, in wrap_socket
    session=session
  File "/usr/local/Cellar/python/3.7.2_1/Frameworks/Python.framework/Versions/3.7/lib/python3.7/ssl.py", line 853, in _create
    self.do_handshake()
  File "/usr/local/Cellar/python/3.7.2_1/Frameworks/Python.framework/Versions/3.7/lib/python3.7/ssl.py", line 1117, in do_handshake
    self._sslobj.do_handshake()
TimeoutError: [Errno 60] Operation timed out

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/requests/adapters.py", line 449, in send
    timeout=timeout
  File "/usr/local/lib/python3.7/site-packages/urllib3/connectionpool.py", line 638, in urlopen
    _stacktrace=sys.exc_info()[2])
  File "/usr/local/lib/python3.7/site-packages/urllib3/util/retry.py", line 367, in increment
    raise six.reraise(type(error), error, _stacktrace)
  File "/usr/local/lib/python3.7/site-packages/urllib3/packages/six.py", line 685, in reraise
    raise value.with_traceback(tb)
  File "/usr/local/lib/python3.7/site-packages/urllib3/connectionpool.py", line 600, in urlopen
    chunked=chunked)
  File "/usr/local/lib/python3.7/site-packages/urllib3/connectionpool.py", line 343, in _make_request
    self._validate_conn(conn)
  File "/usr/local/lib/python3.7/site-packages/urllib3/connectionpool.py", line 839, in _validate_conn
    conn.connect()
  File "/usr/local/lib/python3.7/site-packages/urllib3/connection.py", line 344, in connect
    ssl_context=context)
  File "/usr/local/lib/python3.7/site-packages/urllib3/util/ssl_.py", line 344, in ssl_wrap_socket
    return context.wrap_socket(sock, server_hostname=server_hostname)
  File "/usr/local/Cellar/python/3.7.2_1/Frameworks/Python.framework/Versions/3.7/lib/python3.7/ssl.py", line 412, in wrap_socket
    session=session
  File "/usr/local/Cellar/python/3.7.2_1/Frameworks/Python.framework/Versions/3.7/lib/python3.7/ssl.py", line 853, in _create
    self.do_handshake()
  File "/usr/local/Cellar/python/3.7.2_1/Frameworks/Python.framework/Versions/3.7/lib/python3.7/ssl.py", line 1117, in do_handshake
    self._sslobj.do_handshake()
urllib3.exceptions.ProtocolError: ('Connection aborted.', TimeoutError(60, 'Operation timed out'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/kimbach/Documents/wikilabskultur/batchupload/smkbatch.py", line 207, in TestSMKAPI
    smk_objects=smkapi.get_smk_objects(smk_filter,offset, rows)
  File "/Users/kimbach/Documents/wikilabskultur/batchupload/smkapi.py", line 94, in get_smk_objects
    data=json.loads(requests.get(url).text)
  File "/usr/local/lib/python3.7/site-packages/requests/api.py", line 75, in get
    return request('get', url, params=params, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/requests/api.py", line 60, in request
    return session.request(method=method, url=url, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/requests/sessions.py", line 533, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/local/lib/python3.7/site-packages/requests/sessions.py", line 646, in send
    r = adapter.send(request, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/requests/adapters.py", line 498, in send
    raise ConnectionError(err, request=request)
requests.exceptions.ConnectionError: ('Connection aborted.', TimeoutError(60, 'Operation timed out'))
2021-12-11 12:49:08 Closing network session.
2021-12-11 12:49:08 Network session closed.
2021-12-11 13:05:45 Closing network session.
2021-12-11 13:05:45 Network session closed.
2021-12-11 23:36:35 Closing network session.
2021-12-11 23:36:35 Network session closed.
2021-12-11 23:55:56 Closing network session.
2021-12-11 23:55:56 Network session closed.
2021-12-11 23:58:06 Closing network session.
2021-12-11 23:58:06 Network session closed.
2021-12-12 00:03:58 Closing network session.
2021-12-12 00:03:58 Network session closed.
2021-12-12 00:18:44 __init__() got an unexpected keyword argument 'object_type'
Traceback (most recent call last):
  File "/Users/kimbach/Documents/wikilabskultur/batchupload/smkbatch.py", line 608, in TestSMKAPI
    image_width = smk_image_width)
TypeError: __init__() got an unexpected keyword argument 'object_type'
2021-12-12 00:18:44 __init__() got an unexpected keyword argument 'object_type'
Traceback (most recent call last):
  File "/Users/kimbach/Documents/wikilabskultur/batchupload/smkbatch.py", line 608, in TestSMKAPI
    image_width = smk_image_width)
TypeError: __init__() got an unexpected keyword argument 'object_type'
2021-12-12 00:18:45 __init__() got an unexpected keyword argument 'object_type'
Traceback (most recent call last):
  File "/Users/kimbach/Documents/wikilabskultur/batchupload/smkbatch.py", line 608, in TestSMKAPI
    image_width = smk_image_width)
TypeError: __init__() got an unexpected keyword argument 'object_type'
2021-12-12 00:18:45 __init__() got an unexpected keyword argument 'object_type'
Traceback (most recent call last):
  File "/Users/kimbach/Documents/wikilabskultur/batchupload/smkbatch.py", line 608, in TestSMKAPI
    image_width = smk_image_width)
TypeError: __init__() got an unexpected keyword argument 'object_type'
2021-12-12 00:18:45 __init__() got an unexpected keyword argument 'object_type'
Traceback (most recent call last):
  File "/Users/kimbach/Documents/wikilabskultur/batchupload/smkbatch.py", line 608, in TestSMKAPI
    image_width = smk_image_width)
TypeError: __init__() got an unexpected keyword argument 'object_type'
2021-12-12 00:18:45 __init__() got an unexpected keyword argument 'object_type'
Traceback (most recent call last):
  File "/Users/kimbach/Documents/wikilabskultur/batchupload/smkbatch.py", line 608, in TestSMKAPI
    image_width = smk_image_width)
TypeError: __init__() got an unexpected keyword argument 'object_type'
2021-12-12 00:18:46 __init__() got an unexpected keyword argument 'object_type'
Traceback (most recent call last):
  File "/Users/kimbach/Documents/wikilabskultur/batchupload/smkbatch.py", line 608, in TestSMKAPI
    image_width = smk_image_width)
TypeError: __init__() got an unexpected keyword argument 'object_type'
2021-12-12 00:18:46 __init__() got an unexpected keyword argument 'object_type'
Traceback (most recent call last):
  File "/Users/kimbach/Documents/wikilabskultur/batchupload/smkbatch.py", line 608, in TestSMKAPI
    image_width = smk_image_width)
TypeError: __init__() got an unexpected keyword argument 'object_type'
2021-12-12 00:18:46 __init__() got an unexpected keyword argument 'object_type'
Traceback (most recent call last):
  File "/Users/kimbach/Documents/wikilabskultur/batchupload/smkbatch.py", line 608, in TestSMKAPI
    image_width = smk_image_width)
TypeError: __init__() got an unexpected keyword argument 'object_type'
2021-12-12 00:18:46 __init__() got an unexpected keyword argument 'object_type'
Traceback (most recent call last):
  File "/Users/kimbach/Documents/wikilabskultur/batchupload/smkbatch.py", line 608, in TestSMKAPI
    image_width = smk_image_width)
TypeError: __init__() got an unexpected keyword argument 'object_type'
2021-12-12 00:18:47 Closing network session.
2021-12-12 00:18:47 Network session closed.
2021-12-12 00:20:46 Closing network session.
2021-12-12 00:20:46 Network session closed.
2021-12-12 00:36:11 Closing network session.
2021-12-12 00:36:11 Network session closed.
2021-12-12 00:39:10 Closing network session.
2021-12-12 00:39:10 Network session closed.
2021-12-12 01:15:41 local variable 'smk_titles' referenced before assignment
Traceback (most recent call last):
  File "/Users/kimbach/Documents/wikilabskultur/batchupload/smkbatch.py", line 411, in TestSMKAPI
    smk_titles=smk_titles+'{{' + iso_code +'|' + smk_title + '}}'
UnboundLocalError: local variable 'smk_titles' referenced before assignment
2021-12-12 01:15:41 local variable 'smk_titles' referenced before assignment
Traceback (most recent call last):
  File "/Users/kimbach/Documents/wikilabskultur/batchupload/smkbatch.py", line 411, in TestSMKAPI
    smk_titles=smk_titles+'{{' + iso_code +'|' + smk_title + '}}'
UnboundLocalError: local variable 'smk_titles' referenced before assignment
2021-12-12 01:15:42 local variable 'smk_titles' referenced before assignment
Traceback (most recent call last):
  File "/Users/kimbach/Documents/wikilabskultur/batchupload/smkbatch.py", line 411, in TestSMKAPI
    smk_titles=smk_titles+'{{' + iso_code +'|' + smk_title + '}}'
UnboundLocalError: local variable 'smk_titles' referenced before assignment
2021-12-12 01:15:42 local variable 'smk_titles' referenced before assignment
Traceback (most recent call last):
  File "/Users/kimbach/Documents/wikilabskultur/batchupload/smkbatch.py", line 411, in TestSMKAPI
    smk_titles=smk_titles+'{{' + iso_code +'|' + smk_title + '}}'
UnboundLocalError: local variable 'smk_titles' referenced before assignment
2021-12-12 01:15:42 local variable 'smk_titles' referenced before assignment
Traceback (most recent call last):
  File "/Users/kimbach/Documents/wikilabskultur/batchupload/smkbatch.py", line 411, in TestSMKAPI
    smk_titles=smk_titles+'{{' + iso_code +'|' + smk_title + '}}'
UnboundLocalError: local variable 'smk_titles' referenced before assignment
2021-12-12 01:15:42 local variable 'smk_titles' referenced before assignment
Traceback (most recent call last):
  File "/Users/kimbach/Documents/wikilabskultur/batchupload/smkbatch.py", line 411, in TestSMKAPI
    smk_titles=smk_titles+'{{' + iso_code +'|' + smk_title + '}}'
UnboundLocalError: local variable 'smk_titles' referenced before assignment
2021-12-12 01:15:43 local variable 'smk_titles' referenced before assignment
Traceback (most recent call last):
  File "/Users/kimbach/Documents/wikilabskultur/batchupload/smkbatch.py", line 411, in TestSMKAPI
    smk_titles=smk_titles+'{{' + iso_code +'|' + smk_title + '}}'
UnboundLocalError: local variable 'smk_titles' referenced before assignment
2021-12-12 01:15:43 local variable 'smk_titles' referenced before assignment
Traceback (most recent call last):
  File "/Users/kimbach/Documents/wikilabskultur/batchupload/smkbatch.py", line 411, in TestSMKAPI
    smk_titles=smk_titles+'{{' + iso_code +'|' + smk_title + '}}'
UnboundLocalError: local variable 'smk_titles' referenced before assignment
2021-12-12 01:15:43 local variable 'smk_titles' referenced before assignment
Traceback (most recent call last):
  File "/Users/kimbach/Documents/wikilabskultur/batchupload/smkbatch.py", line 411, in TestSMKAPI
    smk_titles=smk_titles+'{{' + iso_code +'|' + smk_title + '}}'
UnboundLocalError: local variable 'smk_titles' referenced before assignment
2021-12-12 01:15:43 local variable 'smk_titles' referenced before assignment
Traceback (most recent call last):
  File "/Users/kimbach/Documents/wikilabskultur/batchupload/smkbatch.py", line 411, in TestSMKAPI
    smk_titles=smk_titles+'{{' + iso_code +'|' + smk_title + '}}'
UnboundLocalError: local variable 'smk_titles' referenced before assignment
2021-12-12 01:15:44 Closing network session.
2021-12-12 01:15:44 Network session closed.
2021-12-12 01:16:34 bad operand type for unary +: 'str'
Traceback (most recent call last):
  File "/Users/kimbach/Documents/wikilabskultur/batchupload/smkbatch.py", line 619, in TestSMKAPI
    '{{ProvenanceEvent|date='+smk_acquisition_date_precision+'|type=in collection|newowner={{institution:'++'}}}}'
TypeError: bad operand type for unary +: 'str'
2021-12-12 01:16:34 bad operand type for unary +: 'str'
Traceback (most recent call last):
  File "/Users/kimbach/Documents/wikilabskultur/batchupload/smkbatch.py", line 619, in TestSMKAPI
    '{{ProvenanceEvent|date='+smk_acquisition_date_precision+'|type=in collection|newowner={{institution:'++'}}}}'
TypeError: bad operand type for unary +: 'str'
2021-12-12 01:16:34 bad operand type for unary +: 'str'
Traceback (most recent call last):
  File "/Users/kimbach/Documents/wikilabskultur/batchupload/smkbatch.py", line 619, in TestSMKAPI
    '{{ProvenanceEvent|date='+smk_acquisition_date_precision+'|type=in collection|newowner={{institution:'++'}}}}'
TypeError: bad operand type for unary +: 'str'
2021-12-12 01:16:34 bad operand type for unary +: 'str'
Traceback (most recent call last):
  File "/Users/kimbach/Documents/wikilabskultur/batchupload/smkbatch.py", line 619, in TestSMKAPI
    '{{ProvenanceEvent|date='+smk_acquisition_date_precision+'|type=in collection|newowner={{institution:'++'}}}}'
TypeError: bad operand type for unary +: 'str'
2021-12-12 01:16:34 bad operand type for unary +: 'str'
Traceback (most recent call last):
  File "/Users/kimbach/Documents/wikilabskultur/batchupload/smkbatch.py", line 619, in TestSMKAPI
    '{{ProvenanceEvent|date='+smk_acquisition_date_precision+'|type=in collection|newowner={{institution:'++'}}}}'
TypeError: bad operand type for unary +: 'str'
2021-12-12 01:16:35 bad operand type for unary +: 'str'
Traceback (most recent call last):
  File "/Users/kimbach/Documents/wikilabskultur/batchupload/smkbatch.py", line 619, in TestSMKAPI
    '{{ProvenanceEvent|date='+smk_acquisition_date_precision+'|type=in collection|newowner={{institution:'++'}}}}'
TypeError: bad operand type for unary +: 'str'
2021-12-12 01:16:35 bad operand type for unary +: 'str'
Traceback (most recent call last):
  File "/Users/kimbach/Documents/wikilabskultur/batchupload/smkbatch.py", line 619, in TestSMKAPI
    '{{ProvenanceEvent|date='+smk_acquisition_date_precision+'|type=in collection|newowner={{institution:'++'}}}}'
TypeError: bad operand type for unary +: 'str'
2021-12-12 01:16:35 bad operand type for unary +: 'str'
Traceback (most recent call last):
  File "/Users/kimbach/Documents/wikilabskultur/batchupload/smkbatch.py", line 619, in TestSMKAPI
    '{{ProvenanceEvent|date='+smk_acquisition_date_precision+'|type=in collection|newowner={{institution:'++'}}}}'
TypeError: bad operand type for unary +: 'str'
2021-12-12 01:16:35 bad operand type for unary +: 'str'
Traceback (most recent call last):
  File "/Users/kimbach/Documents/wikilabskultur/batchupload/smkbatch.py", line 619, in TestSMKAPI
    '{{ProvenanceEvent|date='+smk_acquisition_date_precision+'|type=in collection|newowner={{institution:'++'}}}}'
TypeError: bad operand type for unary +: 'str'
2021-12-12 01:16:36 bad operand type for unary +: 'str'
Traceback (most recent call last):
  File "/Users/kimbach/Documents/wikilabskultur/batchupload/smkbatch.py", line 619, in TestSMKAPI
    '{{ProvenanceEvent|date='+smk_acquisition_date_precision+'|type=in collection|newowner={{institution:'++'}}}}'
TypeError: bad operand type for unary +: 'str'
2021-12-12 01:16:36 Closing network session.
2021-12-12 01:16:36 Network session closed.
2021-12-12 01:18:21 Closing network session.
2021-12-12 01:18:21 Network session closed.
2021-12-12 01:24:20 Closing network session.
2021-12-12 01:24:20 Network session closed.
2021-12-12 02:40:21 Closing network session.
2021-12-12 02:40:21 Network session closed.
2021-12-12 02:43:54 Closing network session.
2021-12-12 02:43:54 Network session closed.
2021-12-12 02:45:08 Closing network session.
2021-12-12 02:45:08 Network session closed.
2021-12-12 02:46:45 Closing network session.
2021-12-12 02:46:45 Network session closed.
2021-12-12 02:51:44 Closing network session.
2021-12-12 02:51:44 Network session closed.
2021-12-12 02:55:57 Closing network session.
2021-12-12 02:55:57 Network session closed.
2021-12-12 02:56:36 Closing network session.
2021-12-12 02:56:36 Network session closed.
2021-12-12 07:01:33 Closing network session.
2021-12-12 07:01:33 Network session closed.
2021-12-12 07:03:15 Closing network session.
2021-12-12 07:03:15 Network session closed.
2021-12-12 07:17:00 Closing network session.
2021-12-12 07:17:00 Network session closed.
2021-12-12 07:18:38 Closing network session.
2021-12-12 07:18:38 Network session closed.
2021-12-12 08:04:33 Closing network session.
2021-12-12 08:04:33 Network session closed.
2021-12-12 08:07:32 Closing network session.
2021-12-12 08:07:32 Network session closed.
2021-12-12 08:12:12 Closing network session.
2021-12-12 08:12:12 Network session closed.
2021-12-12 08:15:30 Closing network session.
2021-12-12 08:15:30 Network session closed.
2021-12-12 08:45:50 Closing network session.
2021-12-12 08:45:50 Network session closed.
2021-12-12 08:53:06 Closing network session.
2021-12-12 08:53:06 Network session closed.
2021-12-12 09:24:03 'str' object has no attribute 'length'
Traceback (most recent call last):
  File "/Users/kimbach/Documents/wikilabskultur/batchupload/smkbatch.py", line 589, in TestSMKAPI
    if smk_artists_filename[-' - '.length():] == ' - ':
AttributeError: 'str' object has no attribute 'length'
2021-12-12 09:24:17 'str' object has no attribute 'length'
Traceback (most recent call last):
  File "/Users/kimbach/Documents/wikilabskultur/batchupload/smkbatch.py", line 589, in TestSMKAPI
    if smk_artists_filename[-' - '.length():] == ' - ':
AttributeError: 'str' object has no attribute 'length'
2021-12-12 09:25:04 'str' object has no attribute 'length'
Traceback (most recent call last):
  File "/Users/kimbach/Documents/wikilabskultur/batchupload/smkbatch.py", line 589, in TestSMKAPI
    if smk_artists_filename[-' - '.length():] == ' - ':
AttributeError: 'str' object has no attribute 'length'
2021-12-12 09:27:50 count() takes at least 1 argument (0 given)
Traceback (most recent call last):
  File "/Users/kimbach/Documents/wikilabskultur/batchupload/smkbatch.py", line 590, in TestSMKAPI
    smk_artists_filename_delim_length = str(' - ').count()
TypeError: count() takes at least 1 argument (0 given)
2021-12-12 09:27:50 count() takes at least 1 argument (0 given)
Traceback (most recent call last):
  File "/Users/kimbach/Documents/wikilabskultur/batchupload/smkbatch.py", line 590, in TestSMKAPI
    smk_artists_filename_delim_length = str(' - ').count()
TypeError: count() takes at least 1 argument (0 given)
2021-12-12 09:27:50 count() takes at least 1 argument (0 given)
Traceback (most recent call last):
  File "/Users/kimbach/Documents/wikilabskultur/batchupload/smkbatch.py", line 590, in TestSMKAPI
    smk_artists_filename_delim_length = str(' - ').count()
TypeError: count() takes at least 1 argument (0 given)
2021-12-12 09:27:50 count() takes at least 1 argument (0 given)
Traceback (most recent call last):
  File "/Users/kimbach/Documents/wikilabskultur/batchupload/smkbatch.py", line 590, in TestSMKAPI
    smk_artists_filename_delim_length = str(' - ').count()
TypeError: count() takes at least 1 argument (0 given)
2021-12-12 09:27:51 count() takes at least 1 argument (0 given)
Traceback (most recent call last):
  File "/Users/kimbach/Documents/wikilabskultur/batchupload/smkbatch.py", line 590, in TestSMKAPI
    smk_artists_filename_delim_length = str(' - ').count()
TypeError: count() takes at least 1 argument (0 given)
2021-12-12 09:27:51 count() takes at least 1 argument (0 given)
Traceback (most recent call last):
  File "/Users/kimbach/Documents/wikilabskultur/batchupload/smkbatch.py", line 590, in TestSMKAPI
    smk_artists_filename_delim_length = str(' - ').count()
TypeError: count() takes at least 1 argument (0 given)
2021-12-12 09:27:51 count() takes at least 1 argument (0 given)
Traceback (most recent call last):
  File "/Users/kimbach/Documents/wikilabskultur/batchupload/smkbatch.py", line 590, in TestSMKAPI
    smk_artists_filename_delim_length = str(' - ').count()
TypeError: count() takes at least 1 argument (0 given)
2021-12-12 09:27:52 count() takes at least 1 argument (0 given)
Traceback (most recent call last):
  File "/Users/kimbach/Documents/wikilabskultur/batchupload/smkbatch.py", line 590, in TestSMKAPI
    smk_artists_filename_delim_length = str(' - ').count()
TypeError: count() takes at least 1 argument (0 given)
2021-12-12 09:27:52 count() takes at least 1 argument (0 given)
Traceback (most recent call last):
  File "/Users/kimbach/Documents/wikilabskultur/batchupload/smkbatch.py", line 590, in TestSMKAPI
    smk_artists_filename_delim_length = str(' - ').count()
TypeError: count() takes at least 1 argument (0 given)
2021-12-12 09:27:52 count() takes at least 1 argument (0 given)
Traceback (most recent call last):
  File "/Users/kimbach/Documents/wikilabskultur/batchupload/smkbatch.py", line 590, in TestSMKAPI
    smk_artists_filename_delim_length = str(' - ').count()
TypeError: count() takes at least 1 argument (0 given)
2021-12-12 09:27:52 Closing network session.
2021-12-12 09:27:52 Network session closed.
2021-12-12 09:30:08 count() takes at least 1 argument (0 given)
Traceback (most recent call last):
  File "/Users/kimbach/Documents/wikilabskultur/batchupload/smkbatch.py", line 590, in TestSMKAPI
    smk_artists_filename_delim_length = smk_artists_filename_delim.count()
TypeError: count() takes at least 1 argument (0 given)
2021-12-12 09:31:02 'str' object has no attribute 'len'
Traceback (most recent call last):
  File "/Users/kimbach/Documents/wikilabskultur/batchupload/smkbatch.py", line 590, in TestSMKAPI
    smk_artists_filename_delim_length = smk_artists_filename_delim.len()
AttributeError: 'str' object has no attribute 'len'
2021-12-12 09:32:42 string indices must be integers
Traceback (most recent call last):
  File "/Users/kimbach/Documents/wikilabskultur/batchupload/smkbatch.py", line 592, in TestSMKAPI
    smk_artists_filename=smk_artists_filename[0,-smk_artists_filename_delim_length]
TypeError: string indices must be integers
2021-12-12 09:35:26 Closing network session.
2021-12-12 09:35:26 Network session closed.
2021-12-12 09:39:20 Closing network session.
2021-12-12 09:39:20 Network session closed.
2021-12-12 09:45:44 'str' object has no attribute 'tolower'
Traceback (most recent call last):
  File "/Users/kimbach/Documents/wikilabskultur/batchupload/smkbatch.py", line 586, in TestSMKAPI
    if smk_artist.tolower() != 'ubekendt':
AttributeError: 'str' object has no attribute 'tolower'
2021-12-12 09:45:44 'str' object has no attribute 'tolower'
Traceback (most recent call last):
  File "/Users/kimbach/Documents/wikilabskultur/batchupload/smkbatch.py", line 586, in TestSMKAPI
    if smk_artist.tolower() != 'ubekendt':
AttributeError: 'str' object has no attribute 'tolower'
2021-12-12 09:45:44 'str' object has no attribute 'tolower'
Traceback (most recent call last):
  File "/Users/kimbach/Documents/wikilabskultur/batchupload/smkbatch.py", line 586, in TestSMKAPI
    if smk_artist.tolower() != 'ubekendt':
AttributeError: 'str' object has no attribute 'tolower'
2021-12-12 09:45:45 'str' object has no attribute 'tolower'
Traceback (most recent call last):
  File "/Users/kimbach/Documents/wikilabskultur/batchupload/smkbatch.py", line 586, in TestSMKAPI
    if smk_artist.tolower() != 'ubekendt':
AttributeError: 'str' object has no attribute 'tolower'
2021-12-12 09:45:45 'str' object has no attribute 'tolower'
Traceback (most recent call last):
  File "/Users/kimbach/Documents/wikilabskultur/batchupload/smkbatch.py", line 586, in TestSMKAPI
    if smk_artist.tolower() != 'ubekendt':
AttributeError: 'str' object has no attribute 'tolower'
2021-12-12 09:45:45 'str' object has no attribute 'tolower'
Traceback (most recent call last):
  File "/Users/kimbach/Documents/wikilabskultur/batchupload/smkbatch.py", line 586, in TestSMKAPI
    if smk_artist.tolower() != 'ubekendt':
AttributeError: 'str' object has no attribute 'tolower'
2021-12-12 09:45:45 'str' object has no attribute 'tolower'
Traceback (most recent call last):
  File "/Users/kimbach/Documents/wikilabskultur/batchupload/smkbatch.py", line 586, in TestSMKAPI
    if smk_artist.tolower() != 'ubekendt':
AttributeError: 'str' object has no attribute 'tolower'
2021-12-12 09:45:45 'str' object has no attribute 'tolower'
Traceback (most recent call last):
  File "/Users/kimbach/Documents/wikilabskultur/batchupload/smkbatch.py", line 586, in TestSMKAPI
    if smk_artist.tolower() != 'ubekendt':
AttributeError: 'str' object has no attribute 'tolower'
2021-12-12 09:45:46 'str' object has no attribute 'tolower'
Traceback (most recent call last):
  File "/Users/kimbach/Documents/wikilabskultur/batchupload/smkbatch.py", line 586, in TestSMKAPI
    if smk_artist.tolower() != 'ubekendt':
AttributeError: 'str' object has no attribute 'tolower'
2021-12-12 09:45:46 'str' object has no attribute 'tolower'
Traceback (most recent call last):
  File "/Users/kimbach/Documents/wikilabskultur/batchupload/smkbatch.py", line 586, in TestSMKAPI
    if smk_artist.tolower() != 'ubekendt':
AttributeError: 'str' object has no attribute 'tolower'
2021-12-12 09:45:46 Closing network session.
2021-12-12 09:45:46 Network session closed.
2021-12-12 09:47:24 Closing network session.
2021-12-12 09:47:24 Network session closed.
2021-12-12 09:57:44 Closing network session.
2021-12-12 09:57:44 Network session closed.
2021-12-12 10:00:55 Expecting value: line 1 column 1 (char 0)
Traceback (most recent call last):
  File "/Users/kimbach/Documents/wikilabskultur/batchupload/smkbatch.py", line 214, in TestSMKAPI
    smk_objects=smkapi.get_smk_object(current_number)
  File "/Users/kimbach/Documents/wikilabskultur/batchupload/smkapi.py", line 32, in get_smk_object
    data = json.loads(requests.get(url).text)
  File "/usr/local/Cellar/python/3.7.2_1/Frameworks/Python.framework/Versions/3.7/lib/python3.7/json/__init__.py", line 348, in loads
    return _default_decoder.decode(s)
  File "/usr/local/Cellar/python/3.7.2_1/Frameworks/Python.framework/Versions/3.7/lib/python3.7/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/local/Cellar/python/3.7.2_1/Frameworks/Python.framework/Versions/3.7/lib/python3.7/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
2021-12-12 10:00:57 Closing network session.
2021-12-12 10:00:57 Network session closed.
2021-12-12 10:02:48 Closing network session.
2021-12-12 10:02:48 Network session closed.
2021-12-12 10:26:15 Closing network session.
2021-12-12 10:26:15 Network session closed.
2021-12-12 10:28:16 Closing network session.
2021-12-12 10:28:16 Network session closed.
2021-12-12 10:43:09 Closing network session.
2021-12-12 10:43:09 Network session closed.
2021-12-12 11:17:36 local variable 'smk_labels' referenced before assignment
Traceback (most recent call last):
  File "/Users/kimbach/Documents/wikilabskultur/batchupload/smkbatch.py", line 674, in TestSMKAPI
    notes = smk_notes+smk_labels,
UnboundLocalError: local variable 'smk_labels' referenced before assignment
2021-12-12 11:17:36 local variable 'smk_labels' referenced before assignment
Traceback (most recent call last):
  File "/Users/kimbach/Documents/wikilabskultur/batchupload/smkbatch.py", line 674, in TestSMKAPI
    notes = smk_notes+smk_labels,
UnboundLocalError: local variable 'smk_labels' referenced before assignment
2021-12-12 11:17:36 local variable 'smk_labels' referenced before assignment
Traceback (most recent call last):
  File "/Users/kimbach/Documents/wikilabskultur/batchupload/smkbatch.py", line 674, in TestSMKAPI
    notes = smk_notes+smk_labels,
UnboundLocalError: local variable 'smk_labels' referenced before assignment
2021-12-12 11:17:37 local variable 'smk_labels' referenced before assignment
Traceback (most recent call last):
  File "/Users/kimbach/Documents/wikilabskultur/batchupload/smkbatch.py", line 674, in TestSMKAPI
    notes = smk_notes+smk_labels,
UnboundLocalError: local variable 'smk_labels' referenced before assignment
2021-12-12 11:17:37 local variable 'smk_labels' referenced before assignment
Traceback (most recent call last):
  File "/Users/kimbach/Documents/wikilabskultur/batchupload/smkbatch.py", line 674, in TestSMKAPI
    notes = smk_notes+smk_labels,
UnboundLocalError: local variable 'smk_labels' referenced before assignment
2021-12-12 11:17:37 local variable 'smk_labels' referenced before assignment
Traceback (most recent call last):
  File "/Users/kimbach/Documents/wikilabskultur/batchupload/smkbatch.py", line 674, in TestSMKAPI
    notes = smk_notes+smk_labels,
UnboundLocalError: local variable 'smk_labels' referenced before assignment
2021-12-12 11:17:37 local variable 'smk_labels' referenced before assignment
Traceback (most recent call last):
  File "/Users/kimbach/Documents/wikilabskultur/batchupload/smkbatch.py", line 674, in TestSMKAPI
    notes = smk_notes+smk_labels,
UnboundLocalError: local variable 'smk_labels' referenced before assignment
2021-12-12 11:17:38 local variable 'smk_labels' referenced before assignment
Traceback (most recent call last):
  File "/Users/kimbach/Documents/wikilabskultur/batchupload/smkbatch.py", line 674, in TestSMKAPI
    notes = smk_notes+smk_labels,
UnboundLocalError: local variable 'smk_labels' referenced before assignment
2021-12-12 11:17:38 local variable 'smk_labels' referenced before assignment
Traceback (most recent call last):
  File "/Users/kimbach/Documents/wikilabskultur/batchupload/smkbatch.py", line 674, in TestSMKAPI
    notes = smk_notes+smk_labels,
UnboundLocalError: local variable 'smk_labels' referenced before assignment
2021-12-12 11:17:38 local variable 'smk_labels' referenced before assignment
Traceback (most recent call last):
  File "/Users/kimbach/Documents/wikilabskultur/batchupload/smkbatch.py", line 674, in TestSMKAPI
    notes = smk_notes+smk_labels,
UnboundLocalError: local variable 'smk_labels' referenced before assignment
2021-12-12 11:17:38 Closing network session.
2021-12-12 11:17:38 Network session closed.
2021-12-12 11:18:34 Closing network session.
2021-12-12 11:18:34 Network session closed.
2021-12-12 11:19:25 Closing network session.
2021-12-12 11:19:25 Network session closed.
2021-12-12 11:19:42 Closing network session.
2021-12-12 11:19:42 Network session closed.
2021-12-12 11:20:31 Closing network session.
2021-12-12 11:20:31 Network session closed.
2021-12-12 11:25:35 Closing network session.
2021-12-12 11:25:35 Network session closed.
2021-12-12 11:40:06 Closing network session.
2021-12-12 11:40:06 Network session closed.
2021-12-12 11:46:58 Closing network session.
2021-12-12 11:46:58 Network session closed.
2021-12-12 11:51:49 Closing network session.
2021-12-12 11:51:49 Network session closed.
2021-12-12 11:59:02 Closing network session.
2021-12-12 11:59:02 Network session closed.
2021-12-12 11:59:58 Closing network session.
2021-12-12 11:59:58 Network session closed.
2021-12-12 12:10:54 Closing network session.
2021-12-12 12:10:54 Network session closed.
2021-12-12 14:24:57 Closing network session.
2021-12-12 14:24:57 Network session closed.
2021-12-12 14:32:57 Closing network session.
2021-12-12 14:32:57 Network session closed.
2021-12-12 14:44:05 Closing network session.
2021-12-12 14:44:05 Network session closed.
2021-12-12 14:47:52 Closing network session.
2021-12-12 14:47:52 Network session closed.
2021-12-12 16:17:57 Closing network session.
2021-12-12 16:17:57 Network session closed.
2021-12-12 16:19:47 name 'check_image_hash' is not defined
Traceback (most recent call last):
  File "/Users/kimbach/Documents/wikilabskultur/batchupload/smkbatch.py", line 723, in TestSMKAPI
    image_found = check_image_hash(imagepath)
NameError: name 'check_image_hash' is not defined
2021-12-12 16:19:50 Closing network session.
2021-12-12 16:19:50 Network session closed.
2021-12-12 16:22:20 Expecting value: line 1 column 1 (char 0)
Traceback (most recent call last):
  File "/Users/kimbach/Documents/wikilabskultur/batchupload/smkbatch.py", line 723, in TestSMKAPI
    image_found = commons.check_image_hash(imagepath)
  File "/Users/kimbach/Documents/wikilabskultur/batchupload/commons.py", line 259, in check_image_hash
    data = json.loads(requests.get(url).text)
  File "/usr/local/Cellar/python/3.7.2_1/Frameworks/Python.framework/Versions/3.7/lib/python3.7/json/__init__.py", line 348, in loads
    return _default_decoder.decode(s)
  File "/usr/local/Cellar/python/3.7.2_1/Frameworks/Python.framework/Versions/3.7/lib/python3.7/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/local/Cellar/python/3.7.2_1/Frameworks/Python.framework/Versions/3.7/lib/python3.7/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
2021-12-12 16:25:20 Closing network session.
2021-12-12 16:25:20 Network session closed.
2021-12-12 16:27:49 Expecting value: line 1 column 1 (char 0)
Traceback (most recent call last):
  File "/Users/kimbach/Documents/wikilabskultur/batchupload/smkbatch.py", line 723, in TestSMKAPI
    image_found = commons.check_image_hash(imagepath)
  File "/Users/kimbach/Documents/wikilabskultur/batchupload/commons.py", line 259, in check_image_hash
    data = json.loads(requests.get(url).text)
  File "/usr/local/Cellar/python/3.7.2_1/Frameworks/Python.framework/Versions/3.7/lib/python3.7/json/__init__.py", line 348, in loads
    return _default_decoder.decode(s)
  File "/usr/local/Cellar/python/3.7.2_1/Frameworks/Python.framework/Versions/3.7/lib/python3.7/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/local/Cellar/python/3.7.2_1/Frameworks/Python.framework/Versions/3.7/lib/python3.7/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
2021-12-12 16:27:52 Closing network session.
2021-12-12 16:27:52 Network session closed.
2021-12-12 16:30:51 Expecting value: line 1 column 1 (char 0)
Traceback (most recent call last):
  File "/Users/kimbach/Documents/wikilabskultur/batchupload/smkbatch.py", line 723, in TestSMKAPI
    image_found = commons.check_image_hash(imagepath)
  File "/Users/kimbach/Documents/wikilabskultur/batchupload/commons.py", line 259, in check_image_hash
    data = json.loads(requests.get(url).text)
  File "/usr/local/Cellar/python/3.7.2_1/Frameworks/Python.framework/Versions/3.7/lib/python3.7/json/__init__.py", line 348, in loads
    return _default_decoder.decode(s)
  File "/usr/local/Cellar/python/3.7.2_1/Frameworks/Python.framework/Versions/3.7/lib/python3.7/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/local/Cellar/python/3.7.2_1/Frameworks/Python.framework/Versions/3.7/lib/python3.7/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
2021-12-12 16:30:54 Closing network session.
2021-12-12 16:30:54 Network session closed.
2021-12-12 16:53:55 Closing network session.
2021-12-12 16:53:55 Network session closed.
2021-12-12 16:57:36 Closing network session.
2021-12-12 16:57:36 Network session closed.
2021-12-12 19:04:17 Closing network session.
2021-12-12 19:04:17 Network session closed.
2021-12-12 19:06:55 Closing network session.
2021-12-12 19:06:55 Network session closed.
2021-12-12 19:10:40 Closing network session.
2021-12-12 19:10:40 Network session closed.
2021-12-12 19:17:27 Closing network session.
2021-12-12 19:17:27 Network session closed.
2021-12-12 19:19:07 Closing network session.
2021-12-12 19:19:07 Network session closed.
2021-12-12 19:23:36 Closing network session.
2021-12-12 19:23:36 Network session closed.
2021-12-12 19:29:42 Closing network session.
2021-12-12 19:29:42 Network session closed.
2021-12-12 19:31:33 Closing network session.
2021-12-12 19:31:33 Network session closed.
2021-12-12 19:37:47 Closing network session.
2021-12-12 19:37:47 Network session closed.
2021-12-12 19:38:58 Closing network session.
2021-12-12 19:38:58 Network session closed.
2021-12-12 19:43:01 Closing network session.
2021-12-12 19:43:01 Network session closed.
